<?php
$data = [
    ['name'=>'Nasi Goreng Spesial','category'=>'Makanan','price'=>25000],
    ['name'=>'Mie Goreng Jawa','category'=>'Makanan','price'=>22000],
    ['name'=>'Ayam Bakar Taliwang','category'=>'Makanan','price'=>35000],
    ['name'=>'Sate Ayam Madura','category'=>'Makanan','price'=>30000],
    ['name'=>'Nasi Campur Bali','category'=>'Makanan','price'=>35000],
    ['name'=>'Soto Ayam Lamongan','category'=>'Makanan','price'=>20000],
    ['name'=>'Gado-Gado','category'=>'Makanan','price'=>18000],
    ['name'=>'Nasi Kuning','category'=>'Makanan','price'=>15000],
    ['name'=>'Bakso Urat','category'=>'Makanan','price'=>20000],
    ['name'=>'Mie Ayam Jamur','category'=>'Makanan','price'=>18000],
    ['name'=>'Es Teh Manis','category'=>'Minuman','price'=>6000],
    ['name'=>'Es Jeruk Peras','category'=>'Minuman','price'=>8000],
    ['name'=>'Kopi Hitam','category'=>'Minuman','price'=>10000],
    ['name'=>'Cappuccino Dingin','category'=>'Minuman','price'=>18000],
    ['name'=>'Lemon Tea','category'=>'Minuman','price'=>10000],
    ['name'=>'Jus Alpukat','category'=>'Minuman','price'=>15000],
    ['name'=>'Jus Mangga','category'=>'Minuman','price'=>15000],
    ['name'=>'Air Mineral','category'=>'Minuman','price'=>5000],
    ['name'=>'Susu Soda Gembira','category'=>'Minuman','price'=>15000],
    ['name'=>'Thai Tea','category'=>'Minuman','price'=>15000],
    ['name'=>'Kentang Goreng','category'=>'Snack','price'=>15000],
    ['name'=>'Pisang Goreng Keju','category'=>'Snack','price'=>15000],
    ['name'=>'Roti Bakar Coklat','category'=>'Snack','price'=>18000],
    ['name'=>'Mendoan Panas','category'=>'Snack','price'=>12000],
    ['name'=>'Tahu Cabai Garam','category'=>'Snack','price'=>15000],
    ['name'=>'Singkong Goreng','category'=>'Snack','price'=>12000],
    ['name'=>'Onion Rings','category'=>'Snack','price'=>15000],
    ['name'=>'Chicken Wings','category'=>'Snack','price'=>25000],
    ['name'=>'Dimsum Siomay','category'=>'Snack','price'=>18000],
    ['name'=>'Nachos Keju','category'=>'Snack','price'=>25000],
    ['name'=>'Rokok Surya 16','category'=>'Lainnya','price'=>35000],
    ['name'=>'Rokok Sampoerna Mild','category'=>'Lainnya','price'=>33000],
    ['name'=>'Rokok Marlboro Merah','category'=>'Lainnya','price'=>40000],
    ['name'=>'Rokok GG Filter','category'=>'Lainnya','price'=>25000],
    ['name'=>'Permen Mint (Isi 5)','category'=>'Lainnya','price'=>2000],
    ['name'=>'Kopi Sachet Seduh','category'=>'Lainnya','price'=>6000],
    ['name'=>'Indomie Telur Kornet','category'=>'Lainnya','price'=>15000],
    ['name'=>'Pocari Sweat','category'=>'Lainnya','price'=>9000],
    ['name'=>'Kratingdaeng','category'=>'Lainnya','price'=>8000],
    ['name'=>'Korek Api Gas','category'=>'Lainnya','price'=>5000]
];
foreach($data as $item){
    \App\Models\FnbItem::create($item);
}
echo "Data FNB berhasil di-generate!\n";
